package chatter.gui;

import chatter.client.Client;
import javafx.application.Platform;
import javafx.concurrent.Task;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.*;
import javafx.scene.input.KeyCode;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Text;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.InetAddress;
import java.net.URL;
import java.net.UnknownHostException;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.Charset;
import java.nio.charset.CharsetDecoder;
import java.text.SimpleDateFormat;
import java.util.*;


/**
 * Created by jorgelima on 9/30/15.
 */
public class chatController implements Initializable {


    // All the FXML tagged variables are injected by the FXMLLoader
    @FXML
    private Stage mainStage;

    @FXML
    private Button sendMessageButton;

    @FXML
    private TextField textBox;

    @FXML
    private VBox genVBox;

    @FXML
    private Tab genTab;

    @FXML
    private ScrollPane tabScroll;
    @FXML
    private VBox onlineMembers;

    @FXML
    private MenuItem changeNickname;

    private TextInputDialog dialog = new TextInputDialog("itsamemario");

    // Server port
    private int port = 1818;

    // Instance of the Client class
    private Client client;

    // Variable used to verify whether the Client is or not active
    public boolean active = true;

    // Client username, initially defined as null, being generated by an UUID algorithm, can be later modified
    private String userName = null;

    // ArrayList containing the current users on the chat
    private ArrayList<String> userList;


    @Override // This method is called by the FXMLLoader when initialization is complete
    public void initialize(URL fxmlFileLocation, ResourceBundle resources) {

            //Depending on the Server configuration, the client might want to connect to a given address, or directly to localhost for testing purposes

        // Client initialization to a given address
        //client = new Client(port, "152.66.175.216");

        // Client initialization to localhost
        try {
            client = new Client(port, InetAddress.getLocalHost().getHostAddress());
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }

        // Client connection to the server
        client.connectToServer();

        // Assignment of a initial random user name
        userName = getRandomUserName();

        // Initialization of the User List
        userList = new ArrayList<>();


        String join = "joining " + userName;

        // Initial message to the server regarding the connected client username
        client.writeMessage(join);

        // Addition of own username to the User List
        userList.add(userName);

        // Addition of own username to the interface's user list
        addNewUser(userName, true);

        // Loop while the user is active used for receiving all incoming messages
        receiveMessage();


        // Assignment to the text box for proper use of enter button to submit a message
        textBox.setOnKeyPressed(ke -> {
            if (ke.getCode().equals(KeyCode.ENTER))
            {
                String msg = textBox.getText();
                System.out.println(msg);
                client.writeMessage(msg);
                textBox.clear();
            }
        });

        // Scroll the message list to the bottom when new message is received and overflows the current messages box
        genTab.setOnSelectionChanged(arg0 -> tabScroll.setVvalue(1.0));

        // Setting action for the send message button, so it sends when pressed
        sendMessageButton.setOnAction(this::handleButtonAction);

        // Nickname change action
        changeNickname.setOnAction(this::handleChangeNickname);

    }

    // This function let us use the main stage from the chatInterface
    public void setStage(Stage stage)
    {
        this.mainStage = stage;
    }

    // Calling of the Client class shutdown function and setting the active state to false
    public void disconnect() {
        this.active = false;
        client.shutdown();
    }

    // Function that adds a new User to the interface
    public void addNewUser(String name, Boolean own){
        Platform.runLater(() -> {
            Text t;
            t = new Text(name);
            if(own)
                t.setFill(Color.RED);
            else
                t.setFill(Color.BLACK);
            onlineMembers.getChildren().add(t);
        });
    }

    // Function that removes a User from the interface
    public void removeUser(String name){

        System.out.println(name);
        userList.remove(name);

        Platform.runLater(() -> {
            onlineMembers.getChildren().remove(name);
            updateUserList();
        });
    }


    // Function that Updates the userList
    public void updateUserList(){
        onlineMembers.getChildren().clear();
        addNewUser(userName, true);
        for(int i = 0; i < userList.size(); i++){
            String name1 = userList.get(i);
            if(!userName.equals(userList.get(i)))
                addNewUser(name1, false);
        }
    }

    // Function that adds incoming text to the chat box
    public void addTextToTab(String text, Boolean admin){
        Date date = new Date();
        SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss");
        String prep = "[" + df.format(date) + "] " + text;

        Platform.runLater(() -> {
            Text t;
            t = new Text(prep);
            if(text.split("\\s+")[0].equals(userName+":"))
                t.setFill(Color.RED);
            else if(admin)
                t.setFill(Color.DARKORANGE);
            else
                t.setFill(Color.WHITE);
            genVBox.getChildren().add(t);
            tabScroll.setVvalue(1.0);
        });
    }

    // Loop while user is active for receiving incoming messages
    public void receiveMessage(){
        Task rec = new Task<Void>() {
            @Override
            public Void call() throws IOException {
                int nBytes = 0;


                ByteBuffer buffer = ByteBuffer.allocate(2048);
                try {
                    while (active) {
                        while ((nBytes = client.clientSocket.read(buffer)) > 0) {
                            buffer.flip();
                            Charset charset = Charset.forName("UTF-8");
                            CharsetDecoder decoder = charset.newDecoder();
                            CharBuffer charBuffer = decoder.decode(buffer);
                            String result = charBuffer.toString();
                            System.out.println("recebi aqui:" + result);

                            // In this case we received information regarding a user joining the room
                            if (result.split("\\s+")[0].equals("users")) {
                                for(int i = 1; i < result.split("\\s+").length; i++) {
                                    String name = result.split("\\s+")[i];
                                    if(!userList.contains(name))
                                        if (!name.equals(userName)) {
                                            userList.add(name);
                                            addNewUser(name, false);
                                            addTextToTab("Admin: User " + name + " joined the room.", true);
                                        }
                                }
                            }

                            // In this case we received the information of a User disconnection
                            else if(result.split("\\s+")[0].equals("Admin:") && result.split("\\s+")[4].equals("disconnected.")){

                                addTextToTab(result, true);
                                removeUser(result.split("\\s+")[2]);
                            }

                            // In this case we received the information of a User changing his nickname
                            else if(result.split("\\s+")[0].equals("Admin:") && result.split("\\s+")[3].equals("changed")){

                                addTextToTab(result, true);

                                String previous = result.split("\\s+")[2];

                                if (previous.equals(userName)) { //TODO with errors
                                    userName = result.split("\\s+")[7];
                                    removeUser(previous);
                                    System.out.println("userlist: " + userList);
                                }

                                else {
                                    userList.add(result.split("\\s+")[7]);
                                    removeUser(previous);

                                }
                            }

                            // And lastly, we received the information regarding the message to be add to the message box
                            else
                            {
                                addTextToTab(result, false);
                            }
                            buffer.flip();
                        }
                        buffer.clear();
                    }

                } catch (IOException e) {
                    e.printStackTrace();
                }
                return null;
            }
        };

        // Starting of a thread with the task above described
        Thread th = new Thread(rec);
        th.setDaemon(true);

        th.start();
    }

    // Defining the action for the send button pressing ( sending the message to the server )
    private void handleButtonAction(ActionEvent event) {
        String msg = textBox.getText();
        System.out.println(msg);
        client.writeMessage(msg);
        textBox.clear();
    }

    // Defining the action for the changing nickname option
    private void handleChangeNickname(ActionEvent event) {

        final String[] newNick = {null};

        dialog.setTitle("Chatter");
        dialog.setHeaderText("Change your Nickname");
        dialog.setContentText("Please enter your new nick:");
        Optional<String> result = dialog.showAndWait();
        result.ifPresent(name -> newNick[0] = name);
        System.out.println(newNick[0]);
        String join = "changing " + newNick[0];
        client.writeMessage(join);

    }

    // Generation of a random user name using a UUID algorithm
    public String getRandomUserName(){
        String s;
        s = "Anon";
        String ID = UUID.randomUUID().toString().replaceAll("[\\s\\-()]", "");
        return s+ID.substring(3, 10);
    }

}
